# Generated by Django 3.2.5 on 2022-07-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='2020@qq.com', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(default='male', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(default='00001', max_length=32),
        ),
    ]
